version: '3.8'
services:
  api:
    build: ./server
    container_name: api_c
    restart: on-failure
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
  client:
    build: ./client
    container_name: client_c
    restart: on-failure
    ports:
      - "3000:3000" 
    stdin_open: true
    tty: true
    depends_on:
      - api
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./client/.env

